A      NOVELL     APPROACH       FOR     DETECTION      OF                                                                                  LUNG TUMOUR

 
Abstract: 
Delineation of lung tumor from adjacent tissue from different computed tomography images (CT) creates many difficulties due to the similarities in images. In the surrounding areas as well as it influence the respiration. so  accurate segmentation and classification is required in order to detect the present condition of a person. So in order to apply the perfect radiation therapy to the person without effecting the remaining tissues besides the tumor part.  we  are going to use neural networks for classification so that to obtain the accuracy and to improve the parameters for the classification and proper diagnosing  of tumor . this   process  uses the better classification of tumor to  detect and to give the treatment. Therefore we uses the process of  dwt for enhancing the image  and median filter to remove any noise and   to use the GLCM (gray level co occurrence matrix)   for feature extraction and to use the process of neural network classification  for proper classification  to detect the tumor is in initial stage (benign) or it is in final stage (malignant).   

Introduction:
There are many un necessary cells that are grown in our body  the growing of these cells in an un even way in our body can cause many kind of problems. If these kind of cells grows unevenly will make risk to the life of an living being. In bad conditions the growth will be uncertain  . these  lung tumors are mainly formed by cigarettes and also by using different kind of eatables  so that these are the main causes  to grow these cells in an uncertain and also in abnormal manner. these tumors can also mainly contain of different stages . they make the living beings to get in to a situation that  weakens the functions of lungs. Of mixing the functions of oxygen from blood.it is the main causes of cancer in many human beings. The percentage of cancer that most effected by human beings is lung cancer because  of unnecessary activities like smoking. the percentage  of  the people died because of the lung cancer is very high. Approximately 154,050  people died due to lung cancer in 2018. And also the rate has been decreased in 2019  due to the awareness about cancer in some of rural areas  159,292 is in the year 2005. So many people uses the different techniques in order to avoid lung cancer. These cancer occurs due to the uneven growth of tumor in lungs. It is very required for any people to detect lung cancer in the initial stages to save one’s lives. The main purpose of this is to classify it as benign or malignant. The main purpose of this technique is to  use the segmentation and classifying the tumor that it is more accurate and to detect the tumor fast  and to diagnose  in the initial stage  to   cure it. There is no cure for final stage of cancer. to diagnose  it we need to identify it in the initial stage itself. We are going to use Matlab so that to process the image and to enhance the image and to convert the image from gray to binary and also to use the  process of discrete wavelet transform for it and also to use fuzzy means clustering for segmenting the image . we have  used feature extraction technique called GLCM to extract the features of the images . and we are using neural networks for classification. Here in matlab software we are going to create a GUI and by placing different blocks in GUI. So that by using code we need to extract different processes on the GUI. To process  this we need a CT scan image that is computed tomography images to perform operations on the image using  coding format. So we are going to use these  CT scan images and they are essential in image modelling .
LITERAURE SURVEY:
This section represents the survey for  classification  of the tumor from previous references. There are many planning and previous references that are given in order to develop a different set of parameters and different types of algorithms  are used  to  perform  different types of techniques are followed in order to get the required output in different ways
.[1] Humera shaziya etal presented the automatic lung segmentation on thoracic CT scans using U NET Convolutional network they have used unet convolutional networks, deep learning, automatic lung segmentation. . 
[2] ling zhang,etal used an algorithm such that self learning to detect and segment cysts in lung CT images without manual annotation  it was also published in the year of 2018  using unsupervised segmentation,, segmentation networks.
[3] lilkAnifah,etal  used a technique  to detect  cancer lungs detection and ct scan image using artificial neural network back propagation based gray level co occurence  matrices feature. It was published in year 2017 artificial neural network back propagation  based gray level co occurrence matrices.
[4]  Tiany Zhao,et al  uses a technique on lung segmentation in CT images using a fully convolutional neural networks Tiany Zhaol,etal it was published in the year 2018 . it was done with the help of convolutional neural network.
[5] sneha pothagam  uses a technique named multilayer perception based lung tumor classification in the year 2018   algorithm used is k nearest neighbor algorithm 
[6] k.gopi uses a technique named lung tumor area classification (recognition) using EKmean clustering and SVM  and the technique used is SVM,EK thresholding.
[7] zigha zong  uses a technique called 3D fully convolutional N/w’s for cosegmentation of tumors on PETCT images and algorithm used is 3DUnet and graph cut based cosegmentation.
[8] sheenan ratnam used a technique optimized lung cancer classification computed tomography  the algorithm used is BAT algorithm and artificial neural networks.

Methodology:
We are going to use different set of images like normal,benign,malignant to check the image processing  for image classification. We are going to use median filter for  image preprocessing, and to remove any noise  and we used glcm for feature extraction and also we are going to use DWT discrete wavelet transform is used for image enhancement. And we have used neural networks for classification.
